### ISSUE TITLE
Bundling dependencies

### ISSUE THREAD

**Issue by jamesthompson** [thelgevold/rules_svelte#3]
I'm wondering how I would go about bundling an npm dependency using these rules, and also how you would go about building with public resources?

I can't seem to get a reference to `"@npm//$pkg_name_here"` inside the svelte build rule `srcs` to bundle with the demo app you provide. 

Any insights would be greatly appreciated! Thanks a lot for this great work!

**Comment by thelgevold** [comment]
Hi.
Yes that is a good point. I will take a look at that.

**Comment by thelgevold** [comment]
I have added basic support for npm deps. There is an example with lodash in the sample repo.
